name: "Announce Release on Discord"
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  announce-on-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        if: ${{ github.event_name == 'release' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASES_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'ðŸ“£ Platformatic ${{ github.event.release.tag_name }} has been released! Check it out: ${{ github.event.release.html_url }}.'

