name: "DCO Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "DCO Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the DCO document and I hereby sign-off my contribution') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_CLA }}
        with:
          path-to-signatures: 'signatures/version1/dco.json'
          path-to-document: 'https://github.com/platformatic/platformatic/blob/main/dco.txt'
          # branch should not be protected
          branch: 'main'
          allowlist: 'renovate[bot]'
          use-dco-flag: true
          custom-pr-sign-comment: 'I have read the DCO document and I hereby sign-off my contribution'
          signed-commit-message: '$contributorName has signed the DCO in $pullRequestNo'
